# Generated by Django 6.0.4 on 2026-04-26 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0002_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="clubtable",
            name="last_start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
