# Generated by Django 6.0.4 on 2026-04-26 21:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0003_clubtable_last_start_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="start_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
