# Generated by Django 6.0.2 on 2026-04-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0004_alter_booking_start_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_approved",
            field=models.BooleanField(default=False),
        ),
    ]
