# Generated by Django 6.0.2 on 2026-04-27 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0005_user_is_approved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
