# Generated by Django 6.0.2 on 2026-04-27 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0006_alter_user_email_alter_user_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="club.clubtable",
            ),
        ),
    ]
