# Generated by Django 6.0.2 on 2026-04-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0007_transaction_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_looking_for_game",
            field=models.BooleanField(default=False),
        ),
    ]
