# Generated by Django 6.0.2 on 2026-04-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0008_user_is_looking_for_game"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField()),
                (
                    "ann_type",
                    models.CharField(
                        choices=[
                            ("NEWS", "Club News"),
                            ("RULE", "Club Rules"),
                            ("EVENT", "Tournament/Event"),
                        ],
                        default="NEWS",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
    ]
