# Generated by Django 6.0.2 on 2026-04-27 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0009_announcement"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="duration",
            field=models.IntegerField(default=0),
        ),
    ]
