# Generated by Django 6.0.2 on 2026-04-28 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0011_gamerecord"),
    ]

    operations = [
        migrations.RenameField(
            model_name="gamerecord",
            old_name="user_to_pay",
            new_name="user_name",
        ),
        migrations.RemoveField(
            model_name="gamerecord",
            name="session_start_time",
        ),
        migrations.AddField(
            model_name="gamerecord",
            name="is_active_session",
            field=models.BooleanField(default=True),
        ),
    ]
