# Generated by Django 6.0.2 on 2026-04-28 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0012_rename_user_to_pay_gamerecord_user_name_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameRecord",
        ),
    ]
