# Generated by Django 6.0.2 on 2026-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0013_delete_gamerecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="estimated_time",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
