# Generated by Django 6.0.4 on 2026-04-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0014_booking_estimated_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="payment_status",
            field=models.CharField(
                choices=[("PAID", "Paid"), ("UNPAID", "Unpaid")],
                default="UNPAID",
                max_length=10,
            ),
        ),
    ]
